Repository onosproject/ran-simulator, pull requests merged in 2020-02, with the labels that each got.

#12 Added onos-ran to the docker-compose
  build/docker-compose.yaml
  build/sd-ran-gui/nginx-server.conf
  web/sd-ran-gui/src/environments/environment.prod.ts
Labels: enhancement

#16 documentation on how to deploy with Docker-compose and Kubernetes
  README.md
  docs/demo.md
  docs/deployment.md
  docs/docker-compose.md
  docs/images/sd-ran-gui-berlin.png
  docs/sd-ran-gui-deployment.md
Labels: enhancement

#21 Removed TLS on Envoy grpc connection
  Makefile
  README.md
  api/e2/e2-interface.pb.go
  build/envoy-proxy/envoy-proxy.yaml
  docs/README.md
  docs/deployment.md
  docs/docker-compose.md
  go.mod
  web/sd-ran-gui/src/app/onos-sdran/proto/github.com/onosproject/ran-simulator/api/types/types_pb.d.ts
Labels: bug

#23 Added Random Directions generator so not always dependent on Google Directions
  go.sum
  pkg/manager/routes.go
  pkg/manager/routes_test.go
Labels: enhancement

#24 Forward events related to tower proximity of UEs
  api/trafficsim/trafficsim.pb.go
  api/trafficsim/trafficsim.proto
  api/types/types.pb.go
  api/types/types.proto
  cmd/trafficsim/trafficsim.go
  pkg/dispatcher/stream.go
  pkg/manager/locations.go
  pkg/manager/towers.go
  pkg/manager/towers_test.go
  pkg/manager/userequipment.go
  pkg/manager/utils.go
  pkg/manager/utils_test.go
  pkg/northbound/e2/manager.go
  web/sd-ran-gui/src/app/onos-sdran/mapview/mapview.component.html
  web/sd-ran-gui/src/app/onos-sdran/mapview/mapview.component.ts
  web/sd-ran-gui/src/app/onos-sdran/proto/github.com/onosproject/ran-simulator/api/trafficsim/trafficsim_pb.d.ts
  web/sd-ran-gui/src/app/onos-sdran/proto/github.com/onosproject/ran-simulator/api/trafficsim/trafficsim_pb.js
  web/sd-ran-gui/src/app/onos-sdran/proto/github.com/onosproject/ran-simulator/api/types/types_pb.d.ts
  web/sd-ran-gui/src/app/onos-sdran/proto/github.com/onosproject/ran-simulator/api/types/types_pb.js
Labels: enhancement

#29 Fixed the scenario where cars stop driving after a while
  api/trafficsim/trafficsim.pb.go
  api/trafficsim/trafficsim.proto
  api/types/types.pb.go
  api/types/types.proto
  build/docker-compose.yaml
  cmd/trafficsim/trafficsim.go
  docs/README.md
  docs/docker-compose.md
  pkg/dispatcher/dispatcher.go
  pkg/manager/manager.go
  pkg/manager/towers.go
  pkg/manager/userequipment.go
  pkg/manager/utils.go
  pkg/northbound/e2/manager.go
  pkg/northbound/trafficsim/trafficsim.go
  web/sd-ran-gui/src/app/onos-sdran/mapview/mapview.component.ts
  web/sd-ran-gui/src/app/onos-sdran/proto/github.com/onosproject/ran-simulator/api/trafficsim/trafficsimServiceClientPb.ts
  web/sd-ran-gui/src/app/onos-sdran/proto/github.com/onosproject/ran-simulator/api/trafficsim/trafficsim_pb.d.ts
  web/sd-ran-gui/src/app/onos-sdran/proto/github.com/onosproject/ran-simulator/api/trafficsim/trafficsim_pb.js
  web/sd-ran-gui/src/app/onos-sdran/proto/github.com/onosproject/ran-simulator/api/types/types_pb.d.ts
  web/sd-ran-gui/src/app/onos-sdran/proto/github.com/onosproject/ran-simulator/api/types/types_pb.js
  web/sd-ran-gui/src/app/onos-sdran/proto/onos-sdran-trafficsim.service.ts
Labels: bug

#30 Updated GUI to show handover activity
  api/trafficsim/trafficsim.pb.go
  api/trafficsim/trafficsim.proto
  pkg/manager/userequipment.go
  pkg/northbound/e2/manager.go
  pkg/northbound/trafficsim/trafficsim.go
  web/sd-ran-gui/src/app/onos-sdran/mapview/mapview.component.html
  web/sd-ran-gui/src/app/onos-sdran/mapview/mapview.component.ts
  web/sd-ran-gui/src/app/onos-sdran/proto/github.com/onosproject/ran-simulator/api/trafficsim/trafficsim_pb.d.ts
  web/sd-ran-gui/src/app/onos-sdran/proto/github.com/onosproject/ran-simulator/api/trafficsim/trafficsim_pb.js
Labels: bug

#34 Updated docker-compose to pass Google API Key to sdran-gui
  build/docker-compose.yaml
  docs/README.md
  docs/docker-compose.md
  docs/images/sd-ran-gui-berlin.png
  docs/sd-ran-gui-deployment.md
Labels: bug

#37 Corrected how a radio meas report per UE is sent up
  go.mod
  pkg/northbound/e2/manager.go
Labels: bug

#38 Refactored the northbound/e2/manager.go in to control.go and telemetry.go
  cmd/trafficsim/trafficsim.go
  go.mod
  go.sum
  pkg/dispatcher/dispatcher.go
  pkg/manager/locations.go
  pkg/manager/manager.go
  pkg/manager/routes.go
  pkg/manager/towers.go
  pkg/manager/towers_test.go
  pkg/manager/userequipment.go
  pkg/northbound/e2/control.go
  pkg/northbound/e2/control_test.go
  pkg/northbound/e2/e2.go
  pkg/northbound/e2/e2_test.go
  pkg/northbound/e2/manager.go
  pkg/northbound/e2/telemetry.go
  pkg/northbound/trafficsim/trafficsim.go
  pkg/service/server.go
Labels: enhancement

#44 Only send the Radio MeasReport after the UE has been admitted
  api/types/types.pb.go
  api/types/types.proto
  build/docker-compose.yaml
  go.mod
  go.sum
  pkg/manager/userequipment.go
  pkg/northbound/e2/control.go
  pkg/northbound/e2/telemetry.go
  pkg/northbound/e2/telemetry_test.go
Labels: bug

#43 Changed the power to a float and labelled it as dB
  README.md
  api/types/types.pb.go
  api/types/types.proto
  docs/README.md
  pkg/manager/manager.go
  pkg/manager/towers.go
  pkg/manager/userequipment.go
  pkg/northbound/e2/control.go
  pkg/northbound/e2/control_test.go
  pkg/northbound/e2/e2_test.go
  pkg/northbound/e2/telemetry.go
  pkg/northbound/e2/telemetry_test.go
  pkg/northbound/trafficsim/trafficsim.go
Labels: bug

#48 Added in controls to allow setting the number of UEs
  api/trafficsim/trafficsim.pb.go
  api/trafficsim/trafficsim.proto
  api/types/types.pb.go
  api/types/types.proto
  cmd/trafficsim/trafficsim.go
  pkg/manager/manager.go
  pkg/manager/routes.go
  pkg/manager/towers.go
  pkg/manager/userequipment.go
  pkg/northbound/e2/control.go
  pkg/northbound/trafficsim/trafficsim.go
Labels: enhancement

#49 Fixed a deadlock when number of UEs was increased and onos-ran-connected
  cmd/trafficsim/trafficsim.go
  go.mod
  go.sum
  pkg/dispatcher/dispatcher.go
  pkg/northbound/e2/control.go
  pkg/northbound/e2/telemetry.go
Labels: bug

#47 Docs changes for onos-ran -> onos-ric
  api/e2/README.md
  docs/README.md
  docs/deployment.md
Labels: Do Not Merge, documentation

#56 Added in mutexes for updating and reading list of UEs and setting values
  pkg/manager/userequipment.go
  pkg/northbound/e2/control.go
  pkg/northbound/e2/metrics.go
  pkg/northbound/e2/telemetry.go
  pkg/northbound/e2/telemetry_test.go
  pkg/northbound/trafficsim/trafficsim.go
Labels: bug

#54 Added exporting of Latency metric as Prometheus histogram
  cmd/trafficsim/trafficsim.go
  go.mod
  go.sum
  pkg/manager/manager.go
  pkg/northbound/e2/metrics.go
  pkg/northbound/metrics/exporter.go
Labels: enhancement
